@startuml
skinparam style strictuml
skinparam packageStyle rectangle

package View {
  class MainMenü {
  root:BorderPane
  userService:UserService
  taskService:TaskService
  timeLineSettingsService:TimeLineSettingsService
  helperfunctions:Helperfunctions
  isAdminLoggedIn:Boolean
    +start():void
    + showUserSettings():void
    + setupHeader():void
    + showTimeLineMenu():void
    + showAdminMenu():void
    + authenticateAdmin():Boolean
  }

  class Header{
    +init():void
    +showAboutDialog():void
  }

    MainMenü --> Header


package "timeline"{
class TimeLineManager {
    settingsFile:File
    + createView():VBox
    + loadTimeLineSettings():Pair<Int, List<Int>
  }

  class TimeLine{
      timelineContent:Pane
      scrollPane:ScrollPane
      nowPointer:Polygon
      windowStart:LocalDateTime
      windowEnd:LocalDateTime
      + createView(tasks:List<Task>): Pane
      + initAutoScrollToCurrentTime(): void
      + drawTimeMarkers():void
      + drawTasks(tasks:List<Task>):void
      + initTimeUpdater():void
      + createUserHeader(user:User):Hbox
  }

  class TimeLineHeader{
    + init()
    + startClock()
  }

  TimeLineManager --> TimeLineHeader
  TimeLineManager --> TimeLine
}

  package "admin" {

    class AdminMenu {
      content:StackPane
      + createView(): VBox
      + createAdminSettingsHeader(): HBox
      + refreshView(): void
    }

    MainMenü --> TimeLineManager
    MainMenü --> AdminMenu

    class TaskManager {
      + createView(): VBox
      + addTask()
    }

   class TaskOverview {
     + createView(): VBox
     + addTask()
   }

    class AdminSettings {
      + createView(): VBox
      + showUserUpdateDialog()
      + showUserAddModal()
    }

    class TimelineSettings {
          + createView(): VBox
          + loadTimeLineSettings()
          + saveTimeLineSettings()
    }

    class AdminAuthSettings {
      + createView(): VBox
      + updatePassword()
    }

    AdminSettings --> TimelineSettings
    AdminSettings --> AdminAuthSettings
    TaskManager --> TaskOverview

  }

  AdminMenu --> admin.AdminSettings
  AdminMenu --> admin.TaskManager
}

package Controller {
  class GenericController<T> {
   + create(newData:T,routePath:String)
   + read(entityId:Int,userId:Int,newData:T,routePath:String)
   + update(entityId:Int,updatedData:T,routePath:String)
   + delete(entityId:Int,routePath:String)
  }

  MainMenü --> GenericController

}

package Storage {
  interface StorageInterface<T> {
       + checkIfFilePathExists():void
       + create(newData:T,routePath:String)
       + read(entityId:Int,userId:Int,newData:T,routePath:String)
       + update(entityId:Int,updatedData:T,routePath:String)
       + delete(entityId:Int,routePath:String)
       + loadEntities(): List<T>
       + saveEntities(entities:List<T>): void
     }

     class TaskStorage {
       + checkIfFilePathExists():void
       + create(newData:Task,routePath:String)
       + read(entityId:Int,userId:Int,newData:Task,routePath:String)
       + update(entityId:Int,updatedData:Task,routePath:String)
       + delete(entityId:Int,routePath:String)
       + loadEntities(): List<Task>
       + saveEntities(entities:List<Task>): void
       + serializeTask(Task):String
       + parseTask(String):Task
     }

     class UserStorage {
       + checkIfFilePathExists():void
       + initializeCurrentId():void
       + create(newData:User,routePath:String)
       + read(entityId:Int,userId:Int,newData:User,routePath:String)
       + update(entityId:Int,updatedData:User,routePath:String)
       + delete(entityId:Int,routePath:String)
       + loadEntities(): List<User>
       + saveEntities(entities:List<User>): void
     }

     class TimeLineSettingsStorage {
          + checkIfFilePathExists():void
             + create(newData:TimeLineSettings,routePath:String)
             + read(entityId:Int,userId:Int,newData:TimeLineSettings,routePath:String)
             + update(entityId:Int,updatedData:TimeLineSettings,routePath:String)
             + delete(entityId:Int,routePath:String)
             + loadEntities(): List<TimeLineSettings>
             + saveEntities(entities:List<TimeLineSettings>): void
     }

     GenericController --> StorageInterface
     StorageInterface <|.. TaskStorage
     StorageInterface <|.. UserStorage
     StorageInterface <|.. TimeLineSettingsStorage

}

package Model {
  class Task {
     id: Int
     userId: Int
     title: String
     priority: String
     updatedAt: LocalDateTime
     startTime: LocalDateTime
     endTime: LocalDateTime
     deadLine?:LocalDateTime
     status:String,
     imageBase64:String
  }

  class User {
     id: Int
     name: String
     email: String
     password?: String
     role: String
     profileImage:String
    + generateId()
  }

  class TimeLineSettings{
     timeLineCount:Int
     userId:Int
  }

}
}
@enduml